# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 22:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone length has to be 11 & Only number', regex='^\\d{11}$')])),
                ('authenticated_university_email', models.EmailField(max_length=254, unique=True)),
                ('profile_image_path', models.ImageField(blank=True, upload_to='')),
                ('apply_alarm_indexes', models.CharField(default='[]', max_length=200)),
                ('next_meeting_alarm', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_image', models.ImageField(default='meeting_default_image.jpg', upload_to='')),
                ('place', models.CharField(max_length=30)),
                ('leader_image', models.ImageField(default='meeting_leader_default.png', upload_to='')),
                ('leader_talk', models.TextField(default='안녕하세요 :D')),
                ('is_current', models.BooleanField(default=False)),
                ('is_prearranged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_applier', models.IntegerField(default=0)),
                ('created_meeting', models.IntegerField(default=0)),
                ('new_meet_person', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatusByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('max_num_of_members', models.IntegerField(default=6)),
                ('appliers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_by_days', to='meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='SubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(default='meeting_default_image.jpg', upload_to='')),
                ('meeting', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityAuthenticationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('auth_number', models.IntegerField()),
                ('sent_to_user_time', models.DateTimeField()),
                ('auth_number_expiration_time', models.DateTimeField()),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
