# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=1)),
                ('nickname', models.CharField(max_length=20)),
                ('profile_image_path', models.ImageField(blank=True, upload_to='')),
                ('phone_number', models.CharField(max_length=11)),
                ('is_authenticated_university_student', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='distance_near_univ',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='price_range',
        ),
        migrations.AddField(
            model_name='meeting',
            name='category',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='image_paths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='maker_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_num_of_members',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_specific_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='num_of_joined_members',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='place',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='price',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='restaurant_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='specific_link',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='appliers',
            field=models.ManyToManyField(to='meeting.User'),
        ),
    ]
