# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='status_by_days',
        ),
        migrations.AddField(
            model_name='statusbyday',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_by_days', to='meeting.Meeting'),
        ),
    ]
