# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_applier', models.IntegerField(default=0)),
                ('created_meeting', models.IntegerField(default=0)),
                ('new_meet_person', models.IntegerField(default=0)),
            ],
        ),
    ]
