# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20170317_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
