# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_status_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statistics',
        ),
        migrations.RemoveField(
            model_name='statusbyday',
            name='num_of_joined_members',
        ),
        migrations.AddField(
            model_name='user',
            name='apply_alarm_indexes',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
