# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_status_initial'),
        ('meeting', '0003_status'),
    ]

    operations = [
    ]
