# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-16 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_merge_20170416_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Statistics',
        ),
    ]
