# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20170416_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participated_ids',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
