# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20170416_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusbyday',
            name='num_of_joined_members',
        ),
        migrations.AddField(
            model_name='user',
            name='apply_alarm_indexes',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
