# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20170424_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=255)),
            ],
        ),
    ]
