# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_activityneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_meeting_alarm',
            field=models.BooleanField(default=False),
        ),
    ]
