# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_user_participated_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apply_alarm_indexes',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
