# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_user_next_meeting_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_prearranged',
            field=models.BooleanField(default=False),
        ),
    ]
