# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_user_apply_alarm_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusbyday',
            name='num_of_joined_members',
        ),
        migrations.RemoveField(
            model_name='user',
            name='participated_ids',
        ),
    ]
